CREATE DATABASE flashcardapp;
USE [flashcardapp]

SET ANSI_NULLS ON


SET QUOTED_IDENTIFIER ON


CREATE TABLE [dbo].[stacks](
    [id] [int] IDENTITY(1,1) NOT NULL,
    [name] [varchar](255) NULL,
 CONSTRAINT [PK_stacks] PRIMARY KEY CLUSTERED 
(
    [id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

USE [flashcardapp]
SET QUOTED_IDENTIFIER ON


CREATE TABLE [dbo].[flashcards](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[stack_id] [int] NOT NULL,
	[prompt] [varchar](255) NULL,
	[answer] [varchar](255) NULL,
 CONSTRAINT [PK_flashcards] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[flashcards]  WITH CHECK ADD  CONSTRAINT [FK_flashcards_stacks] FOREIGN KEY([stack_id])
REFERENCES [dbo].[stacks] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE

ALTER TABLE [dbo].[flashcards] CHECK CONSTRAINT [FK_flashcards_stacks]
